### ISSUE TITLE
As a staff member, I want to have access to an admin panel on the website, so that I can easily manage and update the recipe collection

### ISSUE THREAD

**Issue by TomsKP** [Intina47/Agile-Group9#1]
### Definition of Done
 - [x] Adheres to company colour scheme.
 - [ ] Adheres to set accessibility guidelines.
 - [ ] Code is well commented.

### Acceptance Criteria
 - [ ] An authorized staff member should be able to add, remove, and edit recipes in the database.
 - [ ] An added recipe must show up in the recipe catalogue.
 - [ ] A removed recipe must no longer show up in the recipe catalogue.
 - [ ] Any changes made to a recipe through editing must show up when viewing the recipe.

### Tasks
 - [x] Design a form for adding a recipe. The form should take the name of the recipe, the steps for the recipe, the list of ingredients, and a picture.
 - [ ] Data must be taken from the form and added to the recipe database.
 - [ ] Test that the recipe is correctly added to the database and shows up on the webpage.
 - [ ] Removing a recipe must remove all the data relating to the recipe from the database. 
 - [ ] Test that the recipe no longer shows up in the catalogue.
 - [ ] Updating a recipe should bring up the original form, and allow the staff member to edit the information. 
 - [ ] This new information must overwrite the original data.
