### ISSUE TITLE
As a customer, I want to be able to share recipes on social media platforms, so that I can share my favorite recipes with others.

### ISSUE THREAD

**Issue by caraticus123** [Intina47/Agile-Group9#10]
### Acceptance Criteria
- [ ] - Recipe page displays a working social media share button
- [ ] - Sharing a recipe creates a post on the user's social media account
- [ ] - The sharing functionality works for both Instagram and Facebook
- [ ] - The post shared on social media should be customizable by the user
- [ ] - Customer should be able to send the recipe to individuals
### Tasks
- [ ] - Implement a "share" button in the recipe page
- [ ] - Find and implement and Instagram and Facebook API
- [ ] - Create a pop-up before the user share which has a pre-generated message and image of the recipe
- [ ] - Make sure user is able to change the caption before they share to their desired social media platform.
- [ ] - The share button should have the appropriate functionality
- [ ] - Test if the button works with the required functionality
### Definition of Done
- [ ] - Adheres to company colour scheme
- [ ] - Adheres to set accessibility guidelines
- [ ] - Code is well commented

Due date:
