### ISSUE TITLE
As a staff member i want a log in page to access admin privileges safely and securely.

### ISSUE THREAD

**Issue by caraticus123** [Intina47/Agile-Group9#15]
### Acceptance criteria
- [ ] - Staff member can access the log in menu
- [ ] - Staff member can safely and securely log in to admin access level

### Tasks
- [x] - add a log in button
- [x] - add a log in form
- [ ] - link to the database
- [ ] - Test the functionality of the login proccess

### Definition of done
- [x] - Adheres to company colour scheme
- [ ] - Adheres to set accessibility guidelines 
- [ ] - Code is well commented
- [ ] - The page is responsive on different device types
