### ISSUE TITLE
As a staff member, I want to be able to search for recipes by category, such as desserts, appetizers, entrees, etc., so that I can easily find recipes that suit customers' needs

### ISSUE THREAD

**Issue by TomsKP** [Intina47/Agile-Group9#2]
### Definition of Done
 - [ ] Adheres to company colour scheme
 - [ ] Adheres to set accessibility guidelines
 - [ ] Code is well commented

### Acceptance Criteria
 - [ ] The search function has categories to filter the recipe database by.

### Tasks
 - [ ] Add a drop-down menu to the search page, which contains a list of categories.
 - [ ] Add checkbox functionality to the list of categories.
 - [ ] Filter the list of recipes by the chosen categories.
