### ISSUE TITLE
As the business owner, I want social media buttons on the webpage, so that customers can easily find our social media accounts.

### ISSUE THREAD

**Issue by TomsKP** [Intina47/Agile-Group9#25]
### Definition of done
- [x] - Adheres to company colour scheme
- [x] - Adheres to set accessibility guidelines 
- [x] - Code is well commented
- [x] - The page is responsive on different device types

### Acceptance Criteria
- [x] - Clicking a social media icon takes the user to the TLGL social media accounts.

### Tasks
- [x] - Add a link to the social media icons.
