### ISSUE TITLE
As a customer, I want to easily browse and search for different recipes based on the ingredients I have on hand or specific dietary restrictions, so that I can make meals that suit my needs.

### ISSUE THREAD

**Issue by EuanRobertson1** [Intina47/Agile-Group9#3]
### Definition of Done
- [ ] Adheres to company colour scheme
- [ ] Adheres to set accessibility guidelines
- [ ] Code is well commented 

### Acceptance Criteria
- [x] Customers are able to use a search bar to search for specific recipes based on keywords
- [ ] Customers are able to filter their search as per dietary needs
- [ ] Customers are able to filter their search based on specific ingredients  
- [ ] Recipes are able to be filtered by popularity, rating, or by newly added 

### Tasks
- [x] Add a UI that displays all available recipes to the Customer 
- [x] Add a search bar to the UI that allows the Customer to find a specific recipe 
- [x] Ensure that the search bar is able to perform a search on the database
- [ ]  Make sure the correct results are returned from database and displayed appropriately on the website.
- [ ] implement a filter feature that allows the Customer to sort the recipe page by popularity, rating , recipes containing certain ingredients , dietary restrictions, and date added
- [ ] Implement a feature to allow the Customer to sort relevant filters by ascending/descending 
- [ ] Implement a feature to allow the Customer to perform a filtered search that only displays results based on the currently applied filters 
- [ ] Ensure all filters are working correctly
