### ISSUE TITLE
As a user, I want the website to have a local map, so that I can easily find the store.

### ISSUE THREAD

**Issue by TomsKP** [Intina47/Agile-Group9#30]
### Definition of Done
 - [x] Adheres to company colour scheme.
 - [ ] Adheres to set accessibility guidelines.
 - [ ] Code is well commented.

### Acceptance Criteria
 - [x] The map should lead customers to the store
 - [ ] Navbar should have a visit us page that includes the map and store information such as opening hours

### Tasks
 - [x] Decide if it's better to have a link that opens a new tab to google maps, or to have a map embedded into the page.
 - [x] If the new tab method is chosen, add a button to the navbar called "Visit Us"
 - [x] If the embedding method is chosen, create a page to house the map. 
 - [x] Add the map to the page.
