### ISSUE TITLE
As a store owner, I want the front page to show videos from the LGL instagram page, so that users can see examples of the company's products.

### ISSUE THREAD

**Issue by TomsKP** [Intina47/Agile-Group9#31]
### Definition of Done
 - [x] Adheres to company colour scheme.
 - [ ] Adheres to set accessibility guidelines.
 - [ ] Code is well commented.

### Acceptance Criteria
 - [x] The front page displays the latest videos from the LGL Instagram feed.
 - [x] Clicking on the video should take you to the relevant Instagram page. 

### Tasks
 - [x] Create a new section in the index page to house the Instagram videos.
 - [x] Create the relevant embed code for the Instagram feed.
 - [x] Embed the Instagram feed into the website. 
 - [x] Test to make sure everything works as it should.
