### ISSUE TITLE
As a customer, I want to be able to save my favourite recipes for easy access in the future, so that I can easily find them when I'm ready to cook.

### ISSUE THREAD

**Issue by EuanRobertson1** [Intina47/Agile-Group9#5]
### Definition of Done
- [x] Adheres to company colour scheme
- [ ] Adheres to set accessibility guidelines
- [ ] Code is well commented

### Acceptance Criteria 
- [x] Customer has an option to download each recipe as a PDF file
- [ ] Customer has an option to save recipes to a personal recipe book
- [ ] Customer can access saved recipes by searching or browsing the recipe book

### Tasks 
- [ ] Add a page that allows Customers to view a full recipe after clicking on a recipe on the recipe browsing page 
- [x] Implement a button to said page that downloads the recipe as a PDF to the Customer's device
- [ ] Implement a personal recipe book for each customer where the can save as many recipes as they please
- [ ] Make sure recipes saved in the book are able to be browsed easily
- [ ] Add a feature that allows the customer to search their recipe book for a specific recipe 
- [ ] Ensure search feature is working properly
