### ISSUE TITLE
As a customer, I want to be able to see a list of all the ingredients needed for a recipe and have the option to add them to my shopping list, so that I can plan my shopping in advance.

### ISSUE THREAD

**Issue by EuanRobertson1** [Intina47/Agile-Group9#7]
### Definition of Done
- [ ] Adheres to company colour scheme
- [ ] Adheres to set accessibility guidelines
- [ ] Code is well commented

### Acceptance Criteria 
- [ ] Customer can view a complete list of ingredients for each recipe on the app
- [ ] Customer is able to add ingredients for a recipe to a shopping list.
- [ ] The shopping list can be sorted by food category
- [ ] Items on the list can be marked as purchased

### Tasks 
- [ ] Add ingredient information to the existing recipe page 
- [ ] Implement a shopping list feature that customers can add one or more recipes to 
- [ ] Ensure the ingredients for each recipe that is added to the shopping list are displayed correctly
- [ ] Ensure that if the same ingredient appears in multiple recipes, it is incremented properly so that the Customer buys the right amount 
- [ ] Add a feature that allows Customer to sort the list by food category
- [ ] Ensure the list sorts properly
- [ ] add a feature that allows the Customer to mark a item on the list as purchased
- [ ] add a feature where items marked as purchased are moved to the bottom of the list
